# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ryan/Coding/C++/Sketch-It

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ryan/Coding/C++/Sketch-It

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ryan/Coding/C++/Sketch-It/CMakeFiles /home/ryan/Coding/C++/Sketch-It//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ryan/Coding/C++/Sketch-It/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named sketch_it

# Build rule for target.
sketch_it: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sketch_it
.PHONY : sketch_it

# fast build rule for target.
sketch_it/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sketch_it.dir/build.make CMakeFiles/sketch_it.dir/build
.PHONY : sketch_it/fast

src/Files/Config.o: src/Files/Config.cpp.o
.PHONY : src/Files/Config.o

# target to build an object file
src/Files/Config.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sketch_it.dir/build.make CMakeFiles/sketch_it.dir/src/Files/Config.cpp.o
.PHONY : src/Files/Config.cpp.o

src/Files/Config.i: src/Files/Config.cpp.i
.PHONY : src/Files/Config.i

# target to preprocess a source file
src/Files/Config.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sketch_it.dir/build.make CMakeFiles/sketch_it.dir/src/Files/Config.cpp.i
.PHONY : src/Files/Config.cpp.i

src/Files/Config.s: src/Files/Config.cpp.s
.PHONY : src/Files/Config.s

# target to generate assembly for a file
src/Files/Config.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sketch_it.dir/build.make CMakeFiles/sketch_it.dir/src/Files/Config.cpp.s
.PHONY : src/Files/Config.cpp.s

src/Files/UserData.o: src/Files/UserData.cpp.o
.PHONY : src/Files/UserData.o

# target to build an object file
src/Files/UserData.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sketch_it.dir/build.make CMakeFiles/sketch_it.dir/src/Files/UserData.cpp.o
.PHONY : src/Files/UserData.cpp.o

src/Files/UserData.i: src/Files/UserData.cpp.i
.PHONY : src/Files/UserData.i

# target to preprocess a source file
src/Files/UserData.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sketch_it.dir/build.make CMakeFiles/sketch_it.dir/src/Files/UserData.cpp.i
.PHONY : src/Files/UserData.cpp.i

src/Files/UserData.s: src/Files/UserData.cpp.s
.PHONY : src/Files/UserData.s

# target to generate assembly for a file
src/Files/UserData.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sketch_it.dir/build.make CMakeFiles/sketch_it.dir/src/Files/UserData.cpp.s
.PHONY : src/Files/UserData.cpp.s

src/Monitor/Monitor.o: src/Monitor/Monitor.cpp.o
.PHONY : src/Monitor/Monitor.o

# target to build an object file
src/Monitor/Monitor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sketch_it.dir/build.make CMakeFiles/sketch_it.dir/src/Monitor/Monitor.cpp.o
.PHONY : src/Monitor/Monitor.cpp.o

src/Monitor/Monitor.i: src/Monitor/Monitor.cpp.i
.PHONY : src/Monitor/Monitor.i

# target to preprocess a source file
src/Monitor/Monitor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sketch_it.dir/build.make CMakeFiles/sketch_it.dir/src/Monitor/Monitor.cpp.i
.PHONY : src/Monitor/Monitor.cpp.i

src/Monitor/Monitor.s: src/Monitor/Monitor.cpp.s
.PHONY : src/Monitor/Monitor.s

# target to generate assembly for a file
src/Monitor/Monitor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sketch_it.dir/build.make CMakeFiles/sketch_it.dir/src/Monitor/Monitor.cpp.s
.PHONY : src/Monitor/Monitor.cpp.s

src/Renderer/Canvas.o: src/Renderer/Canvas.cpp.o
.PHONY : src/Renderer/Canvas.o

# target to build an object file
src/Renderer/Canvas.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sketch_it.dir/build.make CMakeFiles/sketch_it.dir/src/Renderer/Canvas.cpp.o
.PHONY : src/Renderer/Canvas.cpp.o

src/Renderer/Canvas.i: src/Renderer/Canvas.cpp.i
.PHONY : src/Renderer/Canvas.i

# target to preprocess a source file
src/Renderer/Canvas.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sketch_it.dir/build.make CMakeFiles/sketch_it.dir/src/Renderer/Canvas.cpp.i
.PHONY : src/Renderer/Canvas.cpp.i

src/Renderer/Canvas.s: src/Renderer/Canvas.cpp.s
.PHONY : src/Renderer/Canvas.s

# target to generate assembly for a file
src/Renderer/Canvas.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sketch_it.dir/build.make CMakeFiles/sketch_it.dir/src/Renderer/Canvas.cpp.s
.PHONY : src/Renderer/Canvas.cpp.s

src/SketchIt/SketchIt.o: src/SketchIt/SketchIt.cpp.o
.PHONY : src/SketchIt/SketchIt.o

# target to build an object file
src/SketchIt/SketchIt.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sketch_it.dir/build.make CMakeFiles/sketch_it.dir/src/SketchIt/SketchIt.cpp.o
.PHONY : src/SketchIt/SketchIt.cpp.o

src/SketchIt/SketchIt.i: src/SketchIt/SketchIt.cpp.i
.PHONY : src/SketchIt/SketchIt.i

# target to preprocess a source file
src/SketchIt/SketchIt.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sketch_it.dir/build.make CMakeFiles/sketch_it.dir/src/SketchIt/SketchIt.cpp.i
.PHONY : src/SketchIt/SketchIt.cpp.i

src/SketchIt/SketchIt.s: src/SketchIt/SketchIt.cpp.s
.PHONY : src/SketchIt/SketchIt.s

# target to generate assembly for a file
src/SketchIt/SketchIt.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sketch_it.dir/build.make CMakeFiles/sketch_it.dir/src/SketchIt/SketchIt.cpp.s
.PHONY : src/SketchIt/SketchIt.cpp.s

src/SketchIt/SketchItWindow.o: src/SketchIt/SketchItWindow.cpp.o
.PHONY : src/SketchIt/SketchItWindow.o

# target to build an object file
src/SketchIt/SketchItWindow.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sketch_it.dir/build.make CMakeFiles/sketch_it.dir/src/SketchIt/SketchItWindow.cpp.o
.PHONY : src/SketchIt/SketchItWindow.cpp.o

src/SketchIt/SketchItWindow.i: src/SketchIt/SketchItWindow.cpp.i
.PHONY : src/SketchIt/SketchItWindow.i

# target to preprocess a source file
src/SketchIt/SketchItWindow.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sketch_it.dir/build.make CMakeFiles/sketch_it.dir/src/SketchIt/SketchItWindow.cpp.i
.PHONY : src/SketchIt/SketchItWindow.cpp.i

src/SketchIt/SketchItWindow.s: src/SketchIt/SketchItWindow.cpp.s
.PHONY : src/SketchIt/SketchItWindow.s

# target to generate assembly for a file
src/SketchIt/SketchItWindow.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sketch_it.dir/build.make CMakeFiles/sketch_it.dir/src/SketchIt/SketchItWindow.cpp.s
.PHONY : src/SketchIt/SketchItWindow.cpp.s

src/Styles/Styles.o: src/Styles/Styles.cpp.o
.PHONY : src/Styles/Styles.o

# target to build an object file
src/Styles/Styles.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sketch_it.dir/build.make CMakeFiles/sketch_it.dir/src/Styles/Styles.cpp.o
.PHONY : src/Styles/Styles.cpp.o

src/Styles/Styles.i: src/Styles/Styles.cpp.i
.PHONY : src/Styles/Styles.i

# target to preprocess a source file
src/Styles/Styles.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sketch_it.dir/build.make CMakeFiles/sketch_it.dir/src/Styles/Styles.cpp.i
.PHONY : src/Styles/Styles.cpp.i

src/Styles/Styles.s: src/Styles/Styles.cpp.s
.PHONY : src/Styles/Styles.s

# target to generate assembly for a file
src/Styles/Styles.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sketch_it.dir/build.make CMakeFiles/sketch_it.dir/src/Styles/Styles.cpp.s
.PHONY : src/Styles/Styles.cpp.s

src/UI/Components/ErrorModal.o: src/UI/Components/ErrorModal.cpp.o
.PHONY : src/UI/Components/ErrorModal.o

# target to build an object file
src/UI/Components/ErrorModal.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sketch_it.dir/build.make CMakeFiles/sketch_it.dir/src/UI/Components/ErrorModal.cpp.o
.PHONY : src/UI/Components/ErrorModal.cpp.o

src/UI/Components/ErrorModal.i: src/UI/Components/ErrorModal.cpp.i
.PHONY : src/UI/Components/ErrorModal.i

# target to preprocess a source file
src/UI/Components/ErrorModal.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sketch_it.dir/build.make CMakeFiles/sketch_it.dir/src/UI/Components/ErrorModal.cpp.i
.PHONY : src/UI/Components/ErrorModal.cpp.i

src/UI/Components/ErrorModal.s: src/UI/Components/ErrorModal.cpp.s
.PHONY : src/UI/Components/ErrorModal.s

# target to generate assembly for a file
src/UI/Components/ErrorModal.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sketch_it.dir/build.make CMakeFiles/sketch_it.dir/src/UI/Components/ErrorModal.cpp.s
.PHONY : src/UI/Components/ErrorModal.cpp.s

src/UI/Components/SetUp/CanvasDefault.o: src/UI/Components/SetUp/CanvasDefault.cpp.o
.PHONY : src/UI/Components/SetUp/CanvasDefault.o

# target to build an object file
src/UI/Components/SetUp/CanvasDefault.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sketch_it.dir/build.make CMakeFiles/sketch_it.dir/src/UI/Components/SetUp/CanvasDefault.cpp.o
.PHONY : src/UI/Components/SetUp/CanvasDefault.cpp.o

src/UI/Components/SetUp/CanvasDefault.i: src/UI/Components/SetUp/CanvasDefault.cpp.i
.PHONY : src/UI/Components/SetUp/CanvasDefault.i

# target to preprocess a source file
src/UI/Components/SetUp/CanvasDefault.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sketch_it.dir/build.make CMakeFiles/sketch_it.dir/src/UI/Components/SetUp/CanvasDefault.cpp.i
.PHONY : src/UI/Components/SetUp/CanvasDefault.cpp.i

src/UI/Components/SetUp/CanvasDefault.s: src/UI/Components/SetUp/CanvasDefault.cpp.s
.PHONY : src/UI/Components/SetUp/CanvasDefault.s

# target to generate assembly for a file
src/UI/Components/SetUp/CanvasDefault.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sketch_it.dir/build.make CMakeFiles/sketch_it.dir/src/UI/Components/SetUp/CanvasDefault.cpp.s
.PHONY : src/UI/Components/SetUp/CanvasDefault.cpp.s

src/UI/Components/SetUp/CustomToolInputs.o: src/UI/Components/SetUp/CustomToolInputs.cpp.o
.PHONY : src/UI/Components/SetUp/CustomToolInputs.o

# target to build an object file
src/UI/Components/SetUp/CustomToolInputs.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sketch_it.dir/build.make CMakeFiles/sketch_it.dir/src/UI/Components/SetUp/CustomToolInputs.cpp.o
.PHONY : src/UI/Components/SetUp/CustomToolInputs.cpp.o

src/UI/Components/SetUp/CustomToolInputs.i: src/UI/Components/SetUp/CustomToolInputs.cpp.i
.PHONY : src/UI/Components/SetUp/CustomToolInputs.i

# target to preprocess a source file
src/UI/Components/SetUp/CustomToolInputs.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sketch_it.dir/build.make CMakeFiles/sketch_it.dir/src/UI/Components/SetUp/CustomToolInputs.cpp.i
.PHONY : src/UI/Components/SetUp/CustomToolInputs.cpp.i

src/UI/Components/SetUp/CustomToolInputs.s: src/UI/Components/SetUp/CustomToolInputs.cpp.s
.PHONY : src/UI/Components/SetUp/CustomToolInputs.s

# target to generate assembly for a file
src/UI/Components/SetUp/CustomToolInputs.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sketch_it.dir/build.make CMakeFiles/sketch_it.dir/src/UI/Components/SetUp/CustomToolInputs.cpp.s
.PHONY : src/UI/Components/SetUp/CustomToolInputs.cpp.s

src/UI/Components/SetUp/CustomTools.o: src/UI/Components/SetUp/CustomTools.cpp.o
.PHONY : src/UI/Components/SetUp/CustomTools.o

# target to build an object file
src/UI/Components/SetUp/CustomTools.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sketch_it.dir/build.make CMakeFiles/sketch_it.dir/src/UI/Components/SetUp/CustomTools.cpp.o
.PHONY : src/UI/Components/SetUp/CustomTools.cpp.o

src/UI/Components/SetUp/CustomTools.i: src/UI/Components/SetUp/CustomTools.cpp.i
.PHONY : src/UI/Components/SetUp/CustomTools.i

# target to preprocess a source file
src/UI/Components/SetUp/CustomTools.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sketch_it.dir/build.make CMakeFiles/sketch_it.dir/src/UI/Components/SetUp/CustomTools.cpp.i
.PHONY : src/UI/Components/SetUp/CustomTools.cpp.i

src/UI/Components/SetUp/CustomTools.s: src/UI/Components/SetUp/CustomTools.cpp.s
.PHONY : src/UI/Components/SetUp/CustomTools.s

# target to generate assembly for a file
src/UI/Components/SetUp/CustomTools.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sketch_it.dir/build.make CMakeFiles/sketch_it.dir/src/UI/Components/SetUp/CustomTools.cpp.s
.PHONY : src/UI/Components/SetUp/CustomTools.cpp.s

src/UI/Components/SetUp/DefaultSession.o: src/UI/Components/SetUp/DefaultSession.cpp.o
.PHONY : src/UI/Components/SetUp/DefaultSession.o

# target to build an object file
src/UI/Components/SetUp/DefaultSession.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sketch_it.dir/build.make CMakeFiles/sketch_it.dir/src/UI/Components/SetUp/DefaultSession.cpp.o
.PHONY : src/UI/Components/SetUp/DefaultSession.cpp.o

src/UI/Components/SetUp/DefaultSession.i: src/UI/Components/SetUp/DefaultSession.cpp.i
.PHONY : src/UI/Components/SetUp/DefaultSession.i

# target to preprocess a source file
src/UI/Components/SetUp/DefaultSession.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sketch_it.dir/build.make CMakeFiles/sketch_it.dir/src/UI/Components/SetUp/DefaultSession.cpp.i
.PHONY : src/UI/Components/SetUp/DefaultSession.cpp.i

src/UI/Components/SetUp/DefaultSession.s: src/UI/Components/SetUp/DefaultSession.cpp.s
.PHONY : src/UI/Components/SetUp/DefaultSession.s

# target to generate assembly for a file
src/UI/Components/SetUp/DefaultSession.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sketch_it.dir/build.make CMakeFiles/sketch_it.dir/src/UI/Components/SetUp/DefaultSession.cpp.s
.PHONY : src/UI/Components/SetUp/DefaultSession.cpp.s

src/UI/Components/SetUp/DefaultTools.o: src/UI/Components/SetUp/DefaultTools.cpp.o
.PHONY : src/UI/Components/SetUp/DefaultTools.o

# target to build an object file
src/UI/Components/SetUp/DefaultTools.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sketch_it.dir/build.make CMakeFiles/sketch_it.dir/src/UI/Components/SetUp/DefaultTools.cpp.o
.PHONY : src/UI/Components/SetUp/DefaultTools.cpp.o

src/UI/Components/SetUp/DefaultTools.i: src/UI/Components/SetUp/DefaultTools.cpp.i
.PHONY : src/UI/Components/SetUp/DefaultTools.i

# target to preprocess a source file
src/UI/Components/SetUp/DefaultTools.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sketch_it.dir/build.make CMakeFiles/sketch_it.dir/src/UI/Components/SetUp/DefaultTools.cpp.i
.PHONY : src/UI/Components/SetUp/DefaultTools.cpp.i

src/UI/Components/SetUp/DefaultTools.s: src/UI/Components/SetUp/DefaultTools.cpp.s
.PHONY : src/UI/Components/SetUp/DefaultTools.s

# target to generate assembly for a file
src/UI/Components/SetUp/DefaultTools.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sketch_it.dir/build.make CMakeFiles/sketch_it.dir/src/UI/Components/SetUp/DefaultTools.cpp.s
.PHONY : src/UI/Components/SetUp/DefaultTools.cpp.s

src/UI/Components/SetUp/SetUp.o: src/UI/Components/SetUp/SetUp.cpp.o
.PHONY : src/UI/Components/SetUp/SetUp.o

# target to build an object file
src/UI/Components/SetUp/SetUp.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sketch_it.dir/build.make CMakeFiles/sketch_it.dir/src/UI/Components/SetUp/SetUp.cpp.o
.PHONY : src/UI/Components/SetUp/SetUp.cpp.o

src/UI/Components/SetUp/SetUp.i: src/UI/Components/SetUp/SetUp.cpp.i
.PHONY : src/UI/Components/SetUp/SetUp.i

# target to preprocess a source file
src/UI/Components/SetUp/SetUp.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sketch_it.dir/build.make CMakeFiles/sketch_it.dir/src/UI/Components/SetUp/SetUp.cpp.i
.PHONY : src/UI/Components/SetUp/SetUp.cpp.i

src/UI/Components/SetUp/SetUp.s: src/UI/Components/SetUp/SetUp.cpp.s
.PHONY : src/UI/Components/SetUp/SetUp.s

# target to generate assembly for a file
src/UI/Components/SetUp/SetUp.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sketch_it.dir/build.make CMakeFiles/sketch_it.dir/src/UI/Components/SetUp/SetUp.cpp.s
.PHONY : src/UI/Components/SetUp/SetUp.cpp.s

src/UI/Components/SetUp/SetUpNotebookTab.o: src/UI/Components/SetUp/SetUpNotebookTab.cpp.o
.PHONY : src/UI/Components/SetUp/SetUpNotebookTab.o

# target to build an object file
src/UI/Components/SetUp/SetUpNotebookTab.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sketch_it.dir/build.make CMakeFiles/sketch_it.dir/src/UI/Components/SetUp/SetUpNotebookTab.cpp.o
.PHONY : src/UI/Components/SetUp/SetUpNotebookTab.cpp.o

src/UI/Components/SetUp/SetUpNotebookTab.i: src/UI/Components/SetUp/SetUpNotebookTab.cpp.i
.PHONY : src/UI/Components/SetUp/SetUpNotebookTab.i

# target to preprocess a source file
src/UI/Components/SetUp/SetUpNotebookTab.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sketch_it.dir/build.make CMakeFiles/sketch_it.dir/src/UI/Components/SetUp/SetUpNotebookTab.cpp.i
.PHONY : src/UI/Components/SetUp/SetUpNotebookTab.cpp.i

src/UI/Components/SetUp/SetUpNotebookTab.s: src/UI/Components/SetUp/SetUpNotebookTab.cpp.s
.PHONY : src/UI/Components/SetUp/SetUpNotebookTab.s

# target to generate assembly for a file
src/UI/Components/SetUp/SetUpNotebookTab.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sketch_it.dir/build.make CMakeFiles/sketch_it.dir/src/UI/Components/SetUp/SetUpNotebookTab.cpp.s
.PHONY : src/UI/Components/SetUp/SetUpNotebookTab.cpp.s

src/UI/Components/ToolProperty.o: src/UI/Components/ToolProperty.cpp.o
.PHONY : src/UI/Components/ToolProperty.o

# target to build an object file
src/UI/Components/ToolProperty.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sketch_it.dir/build.make CMakeFiles/sketch_it.dir/src/UI/Components/ToolProperty.cpp.o
.PHONY : src/UI/Components/ToolProperty.cpp.o

src/UI/Components/ToolProperty.i: src/UI/Components/ToolProperty.cpp.i
.PHONY : src/UI/Components/ToolProperty.i

# target to preprocess a source file
src/UI/Components/ToolProperty.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sketch_it.dir/build.make CMakeFiles/sketch_it.dir/src/UI/Components/ToolProperty.cpp.i
.PHONY : src/UI/Components/ToolProperty.cpp.i

src/UI/Components/ToolProperty.s: src/UI/Components/ToolProperty.cpp.s
.PHONY : src/UI/Components/ToolProperty.s

# target to generate assembly for a file
src/UI/Components/ToolProperty.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sketch_it.dir/build.make CMakeFiles/sketch_it.dir/src/UI/Components/ToolProperty.cpp.s
.PHONY : src/UI/Components/ToolProperty.cpp.s

src/UI/Layouts.o: src/UI/Layouts.cpp.o
.PHONY : src/UI/Layouts.o

# target to build an object file
src/UI/Layouts.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sketch_it.dir/build.make CMakeFiles/sketch_it.dir/src/UI/Layouts.cpp.o
.PHONY : src/UI/Layouts.cpp.o

src/UI/Layouts.i: src/UI/Layouts.cpp.i
.PHONY : src/UI/Layouts.i

# target to preprocess a source file
src/UI/Layouts.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sketch_it.dir/build.make CMakeFiles/sketch_it.dir/src/UI/Layouts.cpp.i
.PHONY : src/UI/Layouts.cpp.i

src/UI/Layouts.s: src/UI/Layouts.cpp.s
.PHONY : src/UI/Layouts.s

# target to generate assembly for a file
src/UI/Layouts.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sketch_it.dir/build.make CMakeFiles/sketch_it.dir/src/UI/Layouts.cpp.s
.PHONY : src/UI/Layouts.cpp.s

src/UI/UIUtils.o: src/UI/UIUtils.cpp.o
.PHONY : src/UI/UIUtils.o

# target to build an object file
src/UI/UIUtils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sketch_it.dir/build.make CMakeFiles/sketch_it.dir/src/UI/UIUtils.cpp.o
.PHONY : src/UI/UIUtils.cpp.o

src/UI/UIUtils.i: src/UI/UIUtils.cpp.i
.PHONY : src/UI/UIUtils.i

# target to preprocess a source file
src/UI/UIUtils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sketch_it.dir/build.make CMakeFiles/sketch_it.dir/src/UI/UIUtils.cpp.i
.PHONY : src/UI/UIUtils.cpp.i

src/UI/UIUtils.s: src/UI/UIUtils.cpp.s
.PHONY : src/UI/UIUtils.s

# target to generate assembly for a file
src/UI/UIUtils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sketch_it.dir/build.make CMakeFiles/sketch_it.dir/src/UI/UIUtils.cpp.s
.PHONY : src/UI/UIUtils.cpp.s

src/UI/Widgets.o: src/UI/Widgets.cpp.o
.PHONY : src/UI/Widgets.o

# target to build an object file
src/UI/Widgets.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sketch_it.dir/build.make CMakeFiles/sketch_it.dir/src/UI/Widgets.cpp.o
.PHONY : src/UI/Widgets.cpp.o

src/UI/Widgets.i: src/UI/Widgets.cpp.i
.PHONY : src/UI/Widgets.i

# target to preprocess a source file
src/UI/Widgets.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sketch_it.dir/build.make CMakeFiles/sketch_it.dir/src/UI/Widgets.cpp.i
.PHONY : src/UI/Widgets.cpp.i

src/UI/Widgets.s: src/UI/Widgets.cpp.s
.PHONY : src/UI/Widgets.s

# target to generate assembly for a file
src/UI/Widgets.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sketch_it.dir/build.make CMakeFiles/sketch_it.dir/src/UI/Widgets.cpp.s
.PHONY : src/UI/Widgets.cpp.s

src/lib/ToolBuilder.o: src/lib/ToolBuilder.cpp.o
.PHONY : src/lib/ToolBuilder.o

# target to build an object file
src/lib/ToolBuilder.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sketch_it.dir/build.make CMakeFiles/sketch_it.dir/src/lib/ToolBuilder.cpp.o
.PHONY : src/lib/ToolBuilder.cpp.o

src/lib/ToolBuilder.i: src/lib/ToolBuilder.cpp.i
.PHONY : src/lib/ToolBuilder.i

# target to preprocess a source file
src/lib/ToolBuilder.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sketch_it.dir/build.make CMakeFiles/sketch_it.dir/src/lib/ToolBuilder.cpp.i
.PHONY : src/lib/ToolBuilder.cpp.i

src/lib/ToolBuilder.s: src/lib/ToolBuilder.cpp.s
.PHONY : src/lib/ToolBuilder.s

# target to generate assembly for a file
src/lib/ToolBuilder.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sketch_it.dir/build.make CMakeFiles/sketch_it.dir/src/lib/ToolBuilder.cpp.s
.PHONY : src/lib/ToolBuilder.cpp.s

src/lib/Tools.o: src/lib/Tools.cpp.o
.PHONY : src/lib/Tools.o

# target to build an object file
src/lib/Tools.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sketch_it.dir/build.make CMakeFiles/sketch_it.dir/src/lib/Tools.cpp.o
.PHONY : src/lib/Tools.cpp.o

src/lib/Tools.i: src/lib/Tools.cpp.i
.PHONY : src/lib/Tools.i

# target to preprocess a source file
src/lib/Tools.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sketch_it.dir/build.make CMakeFiles/sketch_it.dir/src/lib/Tools.cpp.i
.PHONY : src/lib/Tools.cpp.i

src/lib/Tools.s: src/lib/Tools.cpp.s
.PHONY : src/lib/Tools.s

# target to generate assembly for a file
src/lib/Tools.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sketch_it.dir/build.make CMakeFiles/sketch_it.dir/src/lib/Tools.cpp.s
.PHONY : src/lib/Tools.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sketch_it.dir/build.make CMakeFiles/sketch_it.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sketch_it.dir/build.make CMakeFiles/sketch_it.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sketch_it.dir/build.make CMakeFiles/sketch_it.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... sketch_it"
	@echo "... src/Files/Config.o"
	@echo "... src/Files/Config.i"
	@echo "... src/Files/Config.s"
	@echo "... src/Files/UserData.o"
	@echo "... src/Files/UserData.i"
	@echo "... src/Files/UserData.s"
	@echo "... src/Monitor/Monitor.o"
	@echo "... src/Monitor/Monitor.i"
	@echo "... src/Monitor/Monitor.s"
	@echo "... src/Renderer/Canvas.o"
	@echo "... src/Renderer/Canvas.i"
	@echo "... src/Renderer/Canvas.s"
	@echo "... src/SketchIt/SketchIt.o"
	@echo "... src/SketchIt/SketchIt.i"
	@echo "... src/SketchIt/SketchIt.s"
	@echo "... src/SketchIt/SketchItWindow.o"
	@echo "... src/SketchIt/SketchItWindow.i"
	@echo "... src/SketchIt/SketchItWindow.s"
	@echo "... src/Styles/Styles.o"
	@echo "... src/Styles/Styles.i"
	@echo "... src/Styles/Styles.s"
	@echo "... src/UI/Components/ErrorModal.o"
	@echo "... src/UI/Components/ErrorModal.i"
	@echo "... src/UI/Components/ErrorModal.s"
	@echo "... src/UI/Components/SetUp/CanvasDefault.o"
	@echo "... src/UI/Components/SetUp/CanvasDefault.i"
	@echo "... src/UI/Components/SetUp/CanvasDefault.s"
	@echo "... src/UI/Components/SetUp/CustomToolInputs.o"
	@echo "... src/UI/Components/SetUp/CustomToolInputs.i"
	@echo "... src/UI/Components/SetUp/CustomToolInputs.s"
	@echo "... src/UI/Components/SetUp/CustomTools.o"
	@echo "... src/UI/Components/SetUp/CustomTools.i"
	@echo "... src/UI/Components/SetUp/CustomTools.s"
	@echo "... src/UI/Components/SetUp/DefaultSession.o"
	@echo "... src/UI/Components/SetUp/DefaultSession.i"
	@echo "... src/UI/Components/SetUp/DefaultSession.s"
	@echo "... src/UI/Components/SetUp/DefaultTools.o"
	@echo "... src/UI/Components/SetUp/DefaultTools.i"
	@echo "... src/UI/Components/SetUp/DefaultTools.s"
	@echo "... src/UI/Components/SetUp/SetUp.o"
	@echo "... src/UI/Components/SetUp/SetUp.i"
	@echo "... src/UI/Components/SetUp/SetUp.s"
	@echo "... src/UI/Components/SetUp/SetUpNotebookTab.o"
	@echo "... src/UI/Components/SetUp/SetUpNotebookTab.i"
	@echo "... src/UI/Components/SetUp/SetUpNotebookTab.s"
	@echo "... src/UI/Components/ToolProperty.o"
	@echo "... src/UI/Components/ToolProperty.i"
	@echo "... src/UI/Components/ToolProperty.s"
	@echo "... src/UI/Layouts.o"
	@echo "... src/UI/Layouts.i"
	@echo "... src/UI/Layouts.s"
	@echo "... src/UI/UIUtils.o"
	@echo "... src/UI/UIUtils.i"
	@echo "... src/UI/UIUtils.s"
	@echo "... src/UI/Widgets.o"
	@echo "... src/UI/Widgets.i"
	@echo "... src/UI/Widgets.s"
	@echo "... src/lib/ToolBuilder.o"
	@echo "... src/lib/ToolBuilder.i"
	@echo "... src/lib/ToolBuilder.s"
	@echo "... src/lib/Tools.o"
	@echo "... src/lib/Tools.i"
	@echo "... src/lib/Tools.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

